controllers:
    resource: ../src/Controller/
    type: annotation

api_controllers:
    resource: ../src/Controller/API
    type: annotation
    prefix: '/api'

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/auth/login
